name: Publish PyPI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      pypi

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7

      - run: uv build

      - name: Test cli
        run: uv run --isolated --no-project --with dist/*.whl typstar-anki --help

      - run: uv publish

