name: Setup Nix environment

on:
  workflow_call:
    inputs:
      command:
        type: string
        default: ""
      update:
        type: boolean
        default: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: nixbuild/nix-quick-install-action@v34

      - name: Use latest nvim
        if: ${{ inputs.update }}
        run: nix flake update nixpkgs

      - name: Use cache
        if: ${{ ! inputs.update }}
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}

      - run: ${{ inputs.command }}
        if: ${{ inputs.command != '' }}

