name: Tests

on:
  workflow_call:
    inputs:
      update:
        type: boolean
        default: false

jobs:
  test:
    uses: ./.github/workflows/setup-nix.yml
    with:
      command: nix flake check --print-build-logs --all-systems
      update: ${{ inputs.update }}

  test-lazy:
    uses: ./.github/workflows/setup-nix.yml
    with:
      command: nix develop .#lazy --command just test-lazy
      update: ${{ inputs.update }}

